CREATE USER atlas WITH ENCRYPTED PASSWORD 'atlas';
CREATE DATABASE atlas_forge OWNER atlas;
GRANT ALL PRIVILEGES ON DATABASE atlas_forge TO atlas;
GRANT ALL ON SCHEMA public TO atlas;
GRANT ALL ON ALL TABLES IN SCHEMA public TO atlas;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO atlas;